services:
  - type: web
    name: ai-interview-platform-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://ai-interview-platform-nr7v.vercel.app
      - key: MONGO_URI
        sync: false
